import { renderCssVarBlock, tokenToCssVars } from './cssVar';
import { getDesignToken } from './getDesignToken';

export const DEFAULT_VARS_HEADER =
  '/* AUTO-GENERATED by scripts/gen-default-vars.ts — do not edit. Run `pnpm gen:vars`. */\n';

export function renderDefaultVarsCss(): string {
  return DEFAULT_VARS_HEADER + renderCssVarBlock(':root', tokenToCssVars(getDesignToken()));
}
